import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Plus, Minus } from "lucide-react";
import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

// --- CUSTOM ACCORDION ITEM ---
const FaqItem = ({ question, answer, isOpen, onClick, index }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.1, duration: 0.5 }}
      viewport={{ once: true }}
      className={cn(
        "group rounded-xl border transition-all duration-200",
        // Light Mode
        "bg-white border-zinc-200 hover:border-zinc-300",
        // Dark Mode
        "dark:bg-zinc-900/50 dark:border-zinc-800 dark:hover:border-zinc-700"
      )}
    >
      <button
        onClick={onClick}
        className="flex w-full items-center justify-between p-6 pb-4 text-left"
      >
        <span className="text-[15px] font-medium font-poppins text-zinc-800 dark:text-zinc-200 group-hover:text-black dark:group-hover:text-white transition-colors">
          {question}
        </span>
        
        {/* Animated Icon Wrapper */}
        <div className="relative flex h-5 w-5 items-center justify-center">
            <motion.span
                initial={false}
                animate={{ rotate: isOpen ? 90 : 0, opacity: isOpen ? 0 : 1 }}
                transition={{ duration: 0.2 }}
                className="absolute"
            >
                <Plus className="h-5 w-5 text-zinc-400 dark:text-zinc-500" />
            </motion.span>
            <motion.span
                initial={false}
                animate={{ rotate: isOpen ? 0 : -90, opacity: isOpen ? 1 : 0 }}
                transition={{ duration: 0.2 }}
                className="absolute"
            >
                <Minus className="h-5 w-5 text-zinc-800 dark:text-zinc-200" />
            </motion.span>
        </div>
      </button>
      
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ height: { duration: 0.3, ease: "easeInOut" }, opacity: { duration: 0.2 } }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-6 text-[15px] leading-6 text-zinc-500 dark:text-zinc-400 font-inter">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

// --- MAIN SECTION ---
export function FaqsSection() {
  // State to track which item is open. null = all closed.
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <div 
    id="faq"
    className="mx-auto w-full max-w-3xl px-6 py-24 ">
      
      {/* HEADER */}
      <div className="mb-12 space-y-4 text-center">
        <h2 className="text-3xl font-medium font-spacegrotesk text-zinc-900 dark:text-zinc-100 md:text-4xl">
          Frequently Asked Questions
        </h2>
        <p className="text-zinc-500 dark:text-zinc-400 text-sm font-poppins max-w-sm mx-auto">
          Real questions people ask before trusting another DSA platform.
          Straight answers. No fluff.
        </p>
      </div>

      {/* LIST */}
      <div className="space-y-4">
        {questions.map((item, i) => (
          <FaqItem
            key={item.id}
            index={i}
            question={item.title}
            answer={item.content}
            isOpen={openIndex === i}
            onClick={() => setOpenIndex(openIndex === i ? null : i)}
          />
        ))}
      </div>

      {/* FOOTER TEXT */}
      <p className="mt-12 text-center text-sm font-medium text-zinc-500 dark:text-zinc-400 font-poppins">
        Still confused? That’s fair.
        <a href="#" className="ml-1 text-zinc-900 dark:text-zinc-100 hover:dark:text-zinc-300 hover:text-zinc-800 transition-all ">
          Ask us directly.
        </a>
      </p>
    </div>
  );
}

// --- DATA ---
const questions = [
  {
    id: "item-1",
    title: "What is this platform, exactly?",
    content:
      "It’s a coding practice platform focused on understanding, not grinding. Every problem comes with an AI-generated video explanation that breaks down the intuition, approach, and code step by step.",
  },
  {
    id: "item-2",
    title: "How is this different from LeetCode?",
    content:
      "LeetCode mostly tests you. This platform teaches you. Instead of long editorials and assumptions, you get short video explanations that explain why a solution works — visually and clearly.",
  },
  {
    id: "item-3",
    title: "Are the explanations generated by AI?",
    content:
      "Yes — but not the lazy kind. The AI is trained to explain problems like a human tutor: intuition first, then logic, then code, then complexity. No buzzwords. Just clarity.",
  },
  {
    id: "item-4",
    title: "Can I still try solving problems on my own?",
    content:
      "Absolutely. You’re expected to. The explanation is there when you get stuck or want to verify your thinking — not to replace the learning process.",
  },
  {
    id: "item-5",
    title: "Who is this platform actually for?",
    content:
      "Students preparing for placements, developers brushing up DSA, and anyone tired of pretending editorials make sense. If you want shortcuts, this isn’t for you.",
  },
  {
    id: "item-6",
    title: "Is this beginner-friendly?",
    content:
      "Yes. Problems are structured from basic to advanced, and explanations assume zero hidden knowledge. If something matters, it’s explained.",
  },
  {
    id: "item-7",
    title: "Is it free?",
    content:
      "You can start for free and access a set of problems and explanations. Advanced content and features may be part of a paid plan later — no surprise paywalls.",
  },
];